[build]
  command = "pnpm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "16" # or the version you are using
  NPM_FLAGS = "--legacy-peer-deps"

[build]
  command = "pnpm install && pnpm run build"